---
title: "Distributional models for meta-analysis"
output: html_document
date: '2025-03-03'
---

# Required packages

```{r, warning=FALSE}
suppressMessages({
  library(here)
  library(dplyr)
  library(readr)
  library(tidyr) 
  library(tidyverse)
  library(purrr)
  library(metafor)
  library(clubSandwich)
  library(furrr)
  }) 
# function
source(here("fun","fun.R"))
```

# Data

Load data.

```{r}
# load data
dat <- readRDS(here("dat", "dat.RData"))
```

# LS model

```{r}
# empty lists
res_list0 <- vector("list", length(dat))  
error_list0 <- vector("list", length(dat))  
warning_list0 <- vector("list", length(dat)) 

# fit
pb <- txtProgressBar(min = 0, max = length(dat), style = 3)
for (i in seq_along(dat)) {
  cat("\ndataset", i, "of", length(dat), "...\n") 
  
  tryCatch({
    res <- rma(logOR, logOR.var, scale = ~ 1, data = dat[[i]], 
               control = list(maxiter = 1000, stepadj = 0.5))
    
    res_list0[[i]] <- res
  },
  warning = function(w) {
    message("\n Error in dataset ", i, ": ", w$message)
    warning_list0[[i]] <- conditionMessage(w)  
    res_list0[[i]] <- NA  
  },
  error = function(e) {
    message("\n Warning in dataset ", i, ": ", e$message)
    error_list0[[i]] <- conditionMessage(e)  
    res_list0[[i]] <- NA 
  })
  
  setTxtProgressBar(pb, i)
}
close(pb)


saveRDS(res_list0, here("dat", "res_list0.RData"))
res_list0 <- readRDS(here("dat", "res_list0.RData"))

# look at the result
res_list0[[1]]

# errors or warnings
#which(sapply(res_list0, is.null))
```



# Small-study effects1

```{r}
# empty lists
res_list1 <- vector("list", length(dat))  
error_list1 <- vector("list", length(dat))  
warning_list1 <- vector("list", length(dat)) 

# fit
pb <- txtProgressBar(min = 0, max = length(dat), style = 3)
for (i in seq_along(dat)) {
  cat("\ndataset", i, "of", length(dat), "...\n") 
  
  tryCatch({
    res <- rma(logOR, logOR.var, mods = ~ logOR.var, data = dat[[i]], 
               control = list(maxiter = 1000, stepadj = 0.5))
    
    res_list1[[i]] <- res
  },
  warning = function(w) {
    message("\n Error in dataset ", i, ": ", w$message)
    warning_list1[[i]] <- conditionMessage(w)  
    res_list1[[i]] <- NA  
  },
  error = function(e) {
    message("\n Warning in dataset ", i, ": ", e$message)
    error_list1[[i]] <- conditionMessage(e)  
    res_list1[[i]] <- NA 
  })
  
  setTxtProgressBar(pb, i)
}
close(pb)


saveRDS(res_list1, here("dat", "res_list1.RData"))
res_list1 <- readRDS(here("dat", "res_list1.RData"))

# errors or warnings
#which(sapply(res_list1, is.null))
```


# Small-study effects2

```{r}
# empty lists
res_list2 <- vector("list", length(dat))  
error_list2 <- vector("list", length(dat))  
warning_list2 <- vector("list", length(dat)) 

# fit
pb <- txtProgressBar(min = 0, max = length(dat), style = 3)
for (i in seq_along(dat)) {
  cat("\ndataset", i, "of", length(dat), "...\n") 
  
  tryCatch({
    res <- rma(logOR, logOR.var, mods = ~ logOR.var, scale = ~ logOR.var, data = dat[[i]], 
               control = list(maxiter = 1000, stepadj = 0.5, hessianCtrl=list(r=8)))
    
    res_list2[[i]] <- res
  },
  warning = function(w) {
    message("\n Error in dataset ", i, ": ", w$message)
    warning_list2[[i]] <- conditionMessage(w)  
    res_list2[[i]] <- NA  
  },
  error = function(e) {
    message("\n Warning in dataset ", i, ": ", e$message)
    error_list2[[i]] <- conditionMessage(e)  
    res_list2[[i]] <- NA 
  })
  
  setTxtProgressBar(pb, i)
}
close(pb)


# save
saveRDS(res_list2, here("dat", "res_list2.RData"))
res_list2 <- readRDS(here("dat", "res_list2.RData"))

# errors or warnings
#which(sapply(res_list2, is.null))
```


# Small-study effects3

```{r}
# empty lists
res_list3 <- vector("list", length(dat))  
error_list3 <- vector("list", length(dat))  
warning_list3 <- vector("list", length(dat)) 

# fit
pb <- txtProgressBar(min = 0, max = length(dat), style = 3)
for (i in seq_along(dat)) {
  cat("\ndataset", i, "of", length(dat), "...\n") 
  
  tryCatch({
    res <- rma(logOR, logOR.var, scale = ~ logOR, data = dat[[i]], 
               control = list(maxiter = 1000, stepadj = 0.5, hessianCtrl=list(r=8)))
    
    res_list3[[i]] <- res
  },
  warning = function(w) {
    message("\n Error in dataset ", i, ": ", w$message)
    warning_list3[[i]] <- conditionMessage(w)  
    res_list3[[i]] <- NA  
  },
  error = function(e) {
    message("\n Warning in dataset ", i, ": ", e$message)
    error_list3[[i]] <- conditionMessage(e)  
    res_list3[[i]] <- NA 
  })
  
  setTxtProgressBar(pb, i)
}
close(pb)


# save
saveRDS(res_list3, here("dat", "res_list3.RData"))
res_list3 <- readRDS(here("dat", "res_list3.RData"))

# errors or warnings
#which(sapply(res_list3, is.null))
```
